### ISSUE TITLE
Aborted upload crashes the server

### ISSUE THREAD

**Issue by cburatto** [balderdashy/skipper#49]
Adapter: skipper-gridfs
Basic controller code:

```
req.file('fileTest')
        .upload({

            // You can apply a file upload limit (in bytes)
            maxBytes: maxUpload,
            adapter: require('skipper-gridfs'),
            uri: bucketConnect,
            saveAs : function (__newFileStream,cb) {
                cb(null, __newFileStream.filename);
            }

        }, function whenDone(err, uploadedFiles) {
            if (err) {
                var error = {  "status": 500, "error" : err };
                return res.serverError(error);
            }else {
```

I have a jQuery-File-Upload client ( https://blueimp.github.io/jQuery-File-Upload/ ) impementing the  "cancel" procedure by using jqXHR abort described here (https://github.com/blueimp/jQuery-File-Upload/wiki/API ): 

```
$('button.cancel').click(function (e) {
    jqXHR.abort();
});
```

After the client aborts, the server crashes with the following message:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Request aborted
    at IncomingMessage.onReqAborted (.../node_modules/sails/node_modules/skipper/node_modules/multiparty/index.js:175:17)
    at IncomingMessage.EventEmitter.emit (events.js:92:17)
    at abortIncoming (http.js:1911:11)
    at Socket.serverSocketCloseListener (http.js:1923:5)
    at Socket.EventEmitter.emit (events.js:117:20)
    at TCP.close (net.js:466:12)
```

I've used try/catch but it didn't work, the server crashes anyway.

I am not sure if this is a Skipper issue or a Multiparty issue -- my knowledge stops here ( https://github.com/andrewrk/node-multiparty/blob/master/index.js ):

```
function onReqAborted() {
    waitend = false;
    self.emit('aborted');
    handleError(new Error("Request aborted"));
  }

  function onReqEnd() {
    waitend = false;
  }

  function handleError(err) {
    var first = !self.error;
    if (first) {
      self.error = err;
      req.removeListener('aborted', onReqAborted);
      req.removeListener('end', onReqEnd);
      if (self.destStream) {
        self.destStream.emit('error', err);
      }
    }

    cleanupOpenFiles(self);

    if (first) {
      self.emit('error', err);
    }
  }
```

Any clues?

**Comment by mikermcneil** [comment]
Thanks @cburatto - this is solved in skipper@0.5.4 and skipper-disk@0.5.4

**Comment by jessearmand** [comment]
@mikermcneil I still see the same issue on skipper@0.5.5 . I'm running the sails (at 0.10.5) app behind nginx. But, if I run it locally, and do a local upload it's fine. 

I have also set the `res.setTimeout(0)`. It always happens regardless of what file size is uploaded. I've tried both `skipper-disk` and `skipper-s3`

The crash itself can be prevented by intercepting the error through node's domain API. Upload works, but the previously unhandled error is still emitted. 

Mind explaining how was it being solved on skipper@0.5.4?

Here is the debugging info from skipper:

    Sun, 08 Mar 2015 14:06:44 GMT skipper Set up "maxTimeToWaitForFirstFile" timer for 10000ms
    Acquiring new Upstream for field `avatar`
    Sun, 08 Mar 2015 14:06:44 GMT skipper passed control to app because first file was received
    Sun, 08 Mar 2015 14:06:44 GMT skipper waiting for any text params
    Upstream: Pumping incoming file through field `avatar`
    Sun, 08 Mar 2015 14:06:44 GMT skipper Something is trying to read from Upstream `avatar`...
    Form: emitted `close`
    Sun, 08 Mar 2015 14:06:44 GMT skipper multiparty form closed.
    Sun, 08 Mar 2015 14:06:44 GMT skipper Upstream: No more files will be sent through field `avatar`- clearing timeouts...
    Sun, 08 Mar 2015 14:06:44 GMT skipper Passing control to app...
    Sun, 08 Mar 2015 14:06:44 GMT skipper .upload() called on upstream
    RenamerPump:
    • dirname => undefined
    • field => avatar
    • fd => 06a8fb6c-3e01-44b5-b641-381c288c9aa7.png
    A receiver is finished writing files from Upstream `avatar`.
    (this doesn't necessarily mean any files were actually written...)
    { fd: '06a8fb6c-3e01-44b5-b641-381c288c9aa7.png',
      size: 90487,
      type: 'image/png',
      filename: 'logo.png',
      status: 'bufferingOrWriting',
      field: 'avatar',
      extra:
       { Location: 'https://mybucket.s3.amazonaws.com/06a8fb6c-3e01-44b5-b641-381c288c9aa7.png',
         Bucket: 'mybucket',
         Key: '06a8fb6c-3e01-44b5-b641-381c288c9aa7.png',
         ETag: '"7255fcb1f1a2a609c77891156134c442-1"',
         size: 90487 } }
    Fatal incoming error in Upstream `avatar` ::   (source or user may have cancelled the request)
    Error: Request aborted
    -----------
    undefined
    'Request aborted' - 'Error'
    Sun, 08 Mar 2015 14:06:48 GMT skipper multiparty form emitted error: [Error: Request aborted]
    -----------
    Piping the not-yet-written bytes from incoming file `logo.png` to the memory hole..
    A receiver handling Upstream `avatar` encountered a write error : [Error: Request aborted]
    Fatal incoming error in Upstream `avatar` ::   (source or user may have cancelled the request)
    Error: Request aborted
    -----------
    undefined
    'Request aborted' - 'Error'
    -----------
    Sun, 08 Mar 2015 14:06:48 GMT skipper Connected upstream: Emitting read error on incoming file `logo.png` :: [Error: Request aborted]
    Sun, 08 Mar 2015 14:06:48 GMT skipper Connected upstream: Emitting read error on incoming file `logo.png` :: [Error: Request aborted]

**Comment by jessearmand** [comment]
Another useful information. This problem only occurs if I set `NODE_ENV=production`. 

It doesn't happen if `NODE_ENV=development`.

**Comment by Winangel** [comment]
I confirm this issue, for the moment I am trying to use domain api to catch the error and prevent crashing. I Don't know where it comes from...

**Comment by nitzo** [comment]
I am attempting to build a new adapter and while determining the correct way to respond to errors during upload I encountered the same issue.

After some debugging I discovered that skipper provides an error handler for these cases in prototype.writeFile.js. This handler is registered with the 'once' option meaning it will only be called once.

I think what happens is that the error is emitted twice.
 
Once from the current upstream that is aborted (Because of an error, for example closing the browser tab will close the socket and an error to be emitted) and once from multiparty when the request is aborted  (See index.js in multiparty line 196.) this happens later after you send a response in the callback provided to skipper.upload method.

I tried not to send a response to the client and the server did not crash.

Changing the error handler in skipper from 'once' to 'on' also solved the problem although I am not sure the error processing there is correct if it is called twice. I did not dig in further into skipper so I do not fully understand it's internals. 

Maybe someone can shed light on this?

Thanks!

**Comment by Alaneor** [comment]
For those looking for a permanent solution to avoiding aborted file uploads crashing your server, wrap the upload code in a `domain` and attach a handler to the *error* event:

```js
// In a FileController.js or similar controller...

var domain = require('domain')

module.exports =
{ upload: function uploadFile (req, res) {

    var d = domain.create()
    
    // Intentional noop - only fired when a file upload is aborted and the actual
    // error will be properly passed to the function callback below
    d.on('error', function () {})

    d.run(function safelyUpload () {
      req.file('file').upload({/* Adapter config here */}, function (err, files) {
        // Make sure to handle errors! One of them could also be the
        // aborted upload
        if (err)
          return res.serverError(err)
        // All well, continue as usual with files array
      })
    })
  }
}
```

**Comment by twhtanghk** [comment]
It seems that the abort upload is caused by Nginx ending the socket to nodejs server. Refer to the page about [optimizing nginx](https://engineering.gosquared.com/optimising-nginx-node-js-and-networking-for-heavy-workloads), [keepalive options] (http://nginx.org/en/docs/http/ngx_http_upstream_module.html#keepalive) can temporarily fix the problem. 
```
upstream im {
  server app:8008 max_fails=0 fail_timeout=10s;
  keepalive 16;
}

  location /im/ {
    proxy_pass http://im;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Protocol $scheme;
    proxy_set_header X-Forwarded-Host $host;
    proxy_read_timeout 120s;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
```

Another issue is to handle the abort upload of large file triggered by user. For this case, it is required to provide the handler in prototype.parseReq.js as below. 
```
form.on('part', _.bind(function(part) {
    part.on('error', sails.log.error);

    // Take care of text parameters (i.e. non-files)
    if (!part.filename) {
      this.onTextParam(part);
      return;
    }

    // Custom handler for fields w/ files
    this.onFile(part);
  }, this));
```

**Comment by mattcodez** [comment]
@Alaneor Thanks for the domain idea, solved my crashes. Given that domains are deprecated in Nodejs, is there a more direct way to attach an event handler? Ideally without modifying third party code.

**Comment by Alaneor** [comment]
@mattcodez I think a more direct way to handle this would be to fix the issue in Skipper itself - these errors should be returned in the callback.

PS. Domains are deprecated, but they will not be completely obsoleted until a viable replacement technology has been added to Node. So for the time being, I would consider it okay to use them in situations like these.

**Comment by khalilifar** [comment]
Having the same issue here with skipper 5.5 if file size is bigger than maxBytes the file is created and stays open so when i try to upload another file and overwrite the old one server crashes . 
Any way to close the stream so the broken file can be deleted/overwritten ?

**Comment by mikermcneil** [comment]
> I think a more direct way to handle this would be to fix the issue in Skipper itself - these errors should be returned in the callback.

@Alaneor @mattcodez Definitely-- this has just been a hard one to track down since we haven't been able to reproduce it and there's no failing test :/  The domain solution is a great workaround, but it sucks to have to do that!  Hopefully we can get to the bottom of this soon.


> Having the same issue here with skipper 5.5 if file size is bigger than maxBytes the file is created and stays open so when i try to upload another file and overwrite the old one server crashes .

@khalilifar hmm is the only time you see this if the file size is > than maxBytes?


> This problem only occurs if I set NODE_ENV=production

@jessearmand That's odd- are you still seeing that happen in 0.5.9?

**Comment by khalilifar** [comment]
@mikermcneil yes. it uploads fine when files are < maxBytes but when it's larger, I do get the file size error and  I can send the error back to user but i can't remove the half uploaded file (Not even using windows, file gets removed but it reappears ) until i shut the server down. and if I try to overwrite it server crashes.

**Comment by mikermcneil** [comment]
@khalilifar thanks for the quick follow up!  First off- I'm almost certain you're using Skipper disk, but just checking (because maxBytes is currently enforced at the adapter level).  Now assuming that's the case, here's where it's handled: https://github.com/balderdashy/skipper-disk/blob/721eeb29e676f0c9994c07c7d476226dc5a51cd5/standalone/build-progress-stream.js#L111

And specifically, here's the spot where presumably we're taking care of cleaning up after ourselves in a quota-exceeded scenario: https://github.com/balderdashy/skipper-disk/blob/721eeb29e676f0c9994c07c7d476226dc5a51cd5/standalone/build-progress-stream.js#L122

Directly after that code, already-written bytes are garbage collected.  So just looking at it from 1000 feet here, it could be that there's a race condition happening.  Do you see the issue if you comment out lines 130-134 in [this file](https://github.com/balderdashy/skipper-disk/blob/721eeb29e676f0c9994c07c7d476226dc5a51cd5/standalone/build-progress-stream.js#L131)?

**Comment by khalilifar** [comment]
Thanks for spending time on this, Yes i am using Skipper disk  And No that didn't solve the problem server stills crashes. I get this error when i try to upload a file that is > maxBytes

-------------------------------------------------------------------------------------------------------

```javascript
d:\node\project\node_modules\skipper-disk\standalone\build-progress-stream.js:132
          if (gcErr) return outs__.emit('E_EXCEEDS_UPLOAD_LIMIT',[err].concat(
              ^
ReferenceError: gcErr is not defined
    at gc (d:\node\project\node_modules\skipper-disk\standalone\build-progress-stream.js:132:15)
    at Transform.singleFileProgress (d:\node\project\node_modules\skipper-disk\standalone\build-progress-stream.js:135:9)
    at Transform.emit (events.js:107:17)
    at Transform.__progress__._transform (d:\node\project\node_modules\skipper-disk\standalone\build-progress-stream.js:42:10)
    at Transform._read (_stream_transform.js:179:10)
    at Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:301:12)
    at clearBuffer (_stream_writable.js:411:7)
    at onwrite (_stream_writable.js:344:7)
    at WritableState.onwrite (_stream_writable.js:105:5)
    at afterTransform (_stream_transform.js:99:5)
    at TransformState.afterTransform (_stream_transform.js:74:12)
    at Transform.__progress__._transform (d:\node\project\node_modules\skipper-disk\standalone\build-progress-stream.js:50:5)
    at Transform._read (_stream_transform.js:179:10)
    at Transform.Readable.read (_stream_readable.js:341:10)
    at maybeReadMore_ (_stream_readable.js:449:12)
```

**Comment by khalilifar** [comment]
Sorry I didn't pay attention to the error. the above error is irrelevant i think 
had to comment line 132 as well.
But still that didn't solve the problem either,
I don't think the problem is happening there. the problem is when an error happens, the file is kept open by something. and that's why it can't be removed even using OS, and that's what causes the server crash when you want to overwrite a file that is open by something else.

This the error i get whether those lines are commented out or not when trying to overwrite half uploaded file and then server crashes

``` javascript
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: EPERM, open 'd:\node\project\.tmp\uploads\users\d28b731b-bbb0-4988-ab6f-f3d29adb3105.jpg'
    at Error (native)
```

**Comment by cburatto** [comment]
I don't have this error on skipper disk, only on gridfs (didn't try others). I have the feeling that the problem is that the upstream to gridfs is closed before the server can detect the upload connection is closed. Then, it probably tries to send the data to an upstream that was closed. This could explain why it doesn't happen to skipper disk, since it is still possible to append to a file, even if it is "gone".

**Comment by mikermcneil** [comment]
@cburatto @khalilifar Thanks for the follow up guys- @sgress454 and I are looking into this today.

**Comment by sgress454** [comment]
@khalilifar Sorry for the delay--just getting back to this.  Is it fair to say that the error you are seeing is not directly due to aborting an upload, but occurs after you _retry_ an upload with the same name after a failure?  If so, still a totally valid issue, but would you mind posting a separate report for it?  I'm fairly close (I hope) to cracking the main abort issue, so I'd like to separate your case out if it's different.

**Comment by sgress454** [comment]
Ok, I was able to write a [failing test for this in skipper-adapter-tests](https://github.com/balderdashy/skipper-adapter-tests/blob/3cc2c131e6aef90d8b79768ef816be12eb863843/tests/abort.test.js), then put a fix in Skipper that makes the test pass (at least with skipper-s3).  If anyone who was having this issue wants to pull down Skipper from the master branch and try it in their project, I'd appreciate it.  I'm referring specifically to the issue of Sails crashing when a file upload is aborted.

**Comment by cburatto** [comment]
That's great, thanks a lot for working on this! I'll try whenever possible, but just to answer your previous question: I experience this error just by closing the browser tab -- so this doesn't seem to be a file upload "retry" issue (skipper-gridfs).

**Comment by OwaysisApp** [comment]
+1

**Comment by sgress454** [comment]
@OwaysisApp +1, you have the same problem?  +1, the updated code solves your problem? +1, you agree with @cburatto that I'm great? (appreciated, but not immensely helpful).

FYI the easiest way to test the updated code in your app is:

```
npm install github://balderdashy/skipper
```

and then in config/http.js:

```
module.exports.http = {
  bodyParser: require('skipper'),
  ...rest of file...
}
```

It's important that the bodyParser property be at the top level (module.exports.http), and not under the "middleware" property.

**Comment by OwaysisApp** [comment]
haha sorry, same problem (aborted upload).  Moved over to 'skipper-better-s3', works better.

but best of luck.

**Comment by Alaneor** [comment]
@OwaysisApp As the author of that package, I feel obliged to warn you that the problem discussed here is not fixed nor worked around in any way in skipper-better-s3.

**Comment by sgress454** [comment]
@Alaneor Have you seen this issue using skipper-better-s3?  I'm unable to get the abort test to fail with it, even after removing the patch from Skipper, likely because the underlying aws-sdk code doesn't handle stream errors.  This isn't necessarily a bad thing--how error handling should be delegated between Skipper and the adapters is an open question that is likely at the heart of what caused this issue in the first place.  But if you've crashes due to aborted uploads while using your adapter, I'd like to know more about it since there might be something else going on.

**Comment by Alaneor** [comment]
@sgress454 I just tested this with skipper-filesystem adapter and the crash on upload abort is no longer occuring. Instead, it seems that Skipper properly catches that error and logs a `verbose` message that the request was aborted. Nothing further happens in the file upload lifecycle (ie. my completion function is not called).

Which means the original problem is somehow magically solved on my system. The safeguards I placed in my code (with `domain` wrapping the upload) are not triggered by the behaviour I used to trigger the crash before.

**Skipper:** 0.5.9
**Node:** 5.7.0

Here's the relevant stack trace:

```
Error: Request aborted
at Parser.<anonymous> (/app/node_modules/skipper/lib/multipart.js:45:28)
at emitOne (events.js:90:13)
at Parser.emit (events.js:182:7)
at Upstream.<anonymous> (/app/node_modules/skipper/lib/Parser/prototype.acquireUpstream.js:68:10)
at emitOne (events.js:90:13)
at Upstream.emit (events.js:182:7)
at Upstream.fatalIncomingError (/app/node_modules/skipper/standalone/Upstream/prototype.fatalIncomingError.js:78:8)
at /app/node_modules/skipper/lib/Parser/prototype.parseReq.js:51:10
at Function.forEach (/app/node_modules/skipper/node_modules/lodash/dist/lodash.js:3298:15)
at lodash.ctor.(anonymous function) [as each] (/app/node_modules/skipper/node_modules/lodash/dist/lodash.js:5925:31)
at Form.<anonymous> (/app/node_modules/skipper/lib/Parser/prototype.parseReq.js:50:23)
at emitOne (events.js:95:20)
at Form.emit (events.js:182:7)
at handleError (/app/node_modules/skipper/node_modules/multiparty/index.js:196:12)
at IncomingMessage.onReqAborted (/app/node_modules/skipper/node_modules/multiparty/index.js:175:5)
```

**Comment by sgress454** [comment]
@Alaneor hm, and you're definitely using the published 0.5.9 version of Skipper?  It's not linked to the Github repo or anything?

**Comment by Alaneor** [comment]
I am positive. My _package.json_ even has that version as minimum required:

```json
"skipper": "~0.5.9"
```

**Comment by sgress454** [comment]
I meant linked as in `npm link`.  But I'm guessing you'd remember if you pulled the new Skipper code with `git pull` somewhere.  In any case I never tested the upload abort error with anything besides skipper-s3, since that was the first one I got it to fail with.

**Comment by Alaneor** [comment]
Oh I see - nope, nothing like that.

I am quite sure I got the error with `skipper-filesystem`, and I faintly remember that while debugging it I came to conclusion that this error comes from Skipper itself and not from one of the adapters.

**Comment by sgress454** [comment]
>  this error comes from Skipper itself and not from one of the adapters.

It comes from Skipper trying to handle multiple fatal errors, which may or may not be emitted depending on whether the adapter handles stream errors itself.  In skipper-s3, the knox-mpu-alt module handles stream errors by calling its callback with an error, which bubbles up to a fatal error in Skipper.  In skipper-better-s3, the underlying AWS module doesn't handle stream errors directly, so nothing bubbles up, and Skipper only has to handle the fatal error it gets from the multipart form parser.  Leaving the issue of who should be handling what errors aside, the current patch allows Skipper to basically ignore fatal errors after the first one is handled.

**Comment by dan-astiak** [comment]
@sgress454 Sorry for late answer, yes it does occur when i try to retry an upload, but it happens when skipper _aborts_ the upload due to size limit which is probably the same thing that happens when you cancel an upload mid way. so i think solving the abort problem will solve this problem as well. (if it's solved by successfully  terminating the stream that locks the file and doesn't allow it to be removed/overwritten )

**Comment by khalilifar** [comment]
@sgress454 Sorry for late answer, yes it does occur when i try to retry an upload, but it happens when skipper aborts the upload due to size limit which is probably the same thing that happens when you cancel an upload mid way. so i think solving the abort problem will solve this problem as well. (if it's solved by successfully terminating the stream that locks the file and doesn't allow it to be removed/overwritten )

note:sorry sent this by my friends account by mistake.

**Comment by Nishchit14** [comment]
@mikermcneil 
@sgress454 

I am also facing this problem. 
It would be fine if uploading process goes smooth, and have some example with 100kb file to 100mb size of file upload so we can achieve confidence for file uploading. 

We are facing so many issue with file uploading, And some are only occur in production only.

Recently i got one issue in **production** like when i upload **multipart** `file` with `id` param (file at last in sequence) then some times it uploaded successfully but some times `req.body`, `req.params` logs empty but working so fine in **development**. Our app is heavily dependent on file uploading, so we pull down our app and extend launching date. 
Using `sails 0.12.0` & `skipper 0.5.9`

**Comment by sgress454** [comment]
Hi @Nishchit14, sorry to hear it. Let's try and keep this thread focused on the issues with aborting uploads. If you're having this issue, please try the suggestions above for testing with the patched, master branch of Skipper. 

Are you using SSL in production? If so, please see https://github.com/balderdashy/skipper/issues/71 for a discussion of possible issues that could be related to your intermittent empty request body.

**Comment by stellanor** [comment]
:+1: for @sgress454 's fix. I'm no longer experiencing crashes. Aborted uploads errors are now being caught and returned as 500s. Thanks!

I followed these instructions:

`npm install github://balderdashy/skipper`

and then in config/http.js:

```
module.exports.http = {
  bodyParser: require('skipper'),
  ...rest of file...
}
```

**Comment by sgress454** [comment]
@stellanor glad to hear it, thanks for the update!

**Comment by sgress454** [comment]
@cburatto thanks for all the research. I think the source of the particular issue in this thread is pretty well defined (certain adapters throwing errors that were not being handled properly by Skipper).  If you care to test the patched code (see instructions [here](https://github.com/balderdashy/skipper/issues/49#issuecomment-187995676)) and confirm that aborting a request no longer crashes your server, it'd be much appreciated.  If you think you've uncovered a _different_ issue with Sails or Skipper, feel free to post it in a new thread--just trying to keep this one focused on the error after aborted requests.

**Comment by cburatto** [comment]
Thanks. I am getting npm "Permission denied (publickey)" errors on my work computer, but installation worked from home (fix not tested yet). Is there any instruction regarding keys? It could also be a proxy issue, but other NPM installs work without problem through the proxy.

**Comment by sgress454** [comment]
@cburatto Hm, not sure exactly how NPM works with Github, but you can always just `git clone` Sails into a folder on your system and then symlink to it!

**Comment by cburatto** [comment]
Hi.
I have finally tested with the latest skipper code and the problem persists.I am using `Domain` to catch the errors and have "timed" the events. Here's the sequence:

1) Caught by req.file('file').upload({...}) : 

```
Time: 1457975377365
Stack trace:
Error
    at XXXXXX\api\controllers\BrsController.js:281:14
    at cb (XXXXXX\node_modules\skipper\standalone\Upstream\prototype.upload.js:82:14)
    at Upstream.<anonymous> (XXXXXX\node_modules\skipper\standalone\Upstream\prototype.upload.js:112:12)
    at Upstream.g (events.js:199:16)
    at Upstream.emit (events.js:129:20)
    at Upstream.fatalIncomingError (XXXXXX\node_modules\skipper\standalone\Upstream\prototype.fatalIncomingError.js:96:8)
    at Writable.unableToUpload (XXXXXX\node_modules\skipper\standalone\Upstream\prototype.upload.js:143:10)
    at Writable.g (events.js:199:16)
    at Writable.emit (events.js:129:20)
    at PassThrough.<anonymous> (XXXXXX\node_modules\skipper-gridfs\index.js:226:36)
    at PassThrough.g (events.js:199:16)
    at PassThrough.emit (events.js:129:20)
    at XXXXXX\node_modules\skipper\standalone\Upstream\prototype.fatalIncomingError.js:83:17
    at Function.forEach (XXXXXX\node_modules\skipper\node_modules\lodash\dist\lodash.js:3298:15)
    at lodash.ctor.(anonymous function) [as each] (XXXXXX\node_modules\skipper\node_modules\lodash\dist\lodash.js:5925:31)
    at Upstream.fatalIncomingError (XXXXXX\node_modules\skipper\standalone\Upstream\prototype.fatalIncomingError.js:55:18)
```
Stringified error:
`{}`

2) Caught by Node.js Domain:

```
Time: 1457975377378
Stack Trace:
Error
    at Domain.<anonymous> (XXXXXX\api\controllers\BrsController.js:258:11)
    at Domain.emit (events.js:107:17)
    at Writable.emit (events.js:83:19)
    at Stream.failedToWriteFile (XXXXXX\node_modules\skipper-gridfs\index.js:230:36)
    at Stream.g (events.js:199:16)
    at Stream.emit (events.js:129:20)
    at Stream._error (XXXXXX\node_modules\skipper-gridfs\node_modules\gridfs-stream\lib\writestream.js:190:8)
    at XXXXXX\node_modules\skipper-gridfs\node_modules\gridfs-stream\lib\writestream.js:217:26
    at XXXXXX\node_modules\skipper-gridfs\node_modules\mongodb\lib\mongodb\gridfs\gridstore.js:402:26
    at XXXXXX\node_modules\skipper-gridfs\node_modules\mongodb\lib\mongodb\gridfs\chunk.js:167:13
    at XXXXXX\node_modules\skipper-gridfs\node_modules\mongodb\lib\mongodb\collection\core.js:111:18
    at XXXXXX\node_modules\skipper-gridfs\node_modules\mongodb\lib\mongodb\db.js:1193:22
    at bound (domain.js:254:14)
    at runBound (domain.js:267:12)
    at XXXXXX\node_modules\skipper-gridfs\node_modules\mongodb\lib\mongodb\db.js:1905:9
    at bound (domain.js:254:14)
```
		
Stringified error:

```
{
  "name": "MongoError",
  "domainEmitter": {
    "_writableState": {
      "objectMode": true,
      "highWaterMark": 16,
      "needDrain": false,
      "ending": false,
      "ended": false,
      "finished": false,
      "decodeStrings": true,
      "defaultEncoding": "utf8",
      "length": 0,
      "writing": false,
      "corked": 0,
      "sync": false,
      "bufferProcessing": false,
      "writecb": null,
      "writelen": 0,
      "bufferedRequest": null,
      "lastBufferedRequest": null,
      "pendingcb": 0,
      "prefinished": false,
      "errorEmitted": false
    },
    "writable": true,
    "domain": {
      "domain": null,
      "_events": {},
      "members": []
    },
    "_events": {
      "finish": [
        null
      ]
    }
  },
  "domain": {
    "domain": null,
    "_events": {},
    "members": []
  },
  "domainThrown": false
}
```

Please let me know if you need any information.

Cheers.

**Comment by 1nstinct** [comment]
While waiting for the decision I've commented string, where an exception is throwing .../node_modules/skipper-gridfs/index.js:211

**Comment by cburatto** [comment]
I have created a pull request and merged on the skipper-gridfs adapter. Basically, it checks if an error was emitted and, if so, does not emit subsequent ones. It also avoids calling the callback after first error (this seems to have been causing the second error mentioned on https://github.com/willhuang85/skipper-gridfs/issues/20

It is working on my environment: server does not crash. Please check: https://github.com/willhuang85/skipper-gridfs/pull/26

I am not sure if this should be filed as a bug for `skipper-gridfs` or if it should remain here. I suppose `skipper` should have a standard way to deal with misbehaving adapters and catch these types of issues, like @sgress454 is trying to implement.

**Comment by vishnumishra** [comment]
I'm using the     "skipper": "^0.5.9"  and  "skipper-s3": "^0.5.6" but still I'm getting the error.


```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Request aborted
    at IncomingMessage.onReqAborted(/node_modules/skipper/node_modules/multiparty/index.js:175:17)
    at emitNone (events.js:67:13)
    at IncomingMessage.emit (events.js:166:7)
    at abortIncoming (_http_server.js:280:11)
    at Socket.socketOnEnd (_http_server.js:425:7)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickDomainCallback (node.js:396:17)

```
Quick solution I found is to use the Domain level exception handling, but "domain" is deprecated in the node ^4.2  so what I have to use.

How to fix this without domain.

**Comment by mjasnikovs** [comment]
`
error: error: uploadImages Error: Request aborted
    at IncomingMessage.onReqAborted (/home/vagrant/code/node_modules/skipper/node_modules/multiparty/index.js:175:17)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at abortIncoming (_http_server.js:280:11)
    at Socket.socketOnEnd (_http_server.js:431:7)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9) undefined
`
Same

**Comment by sgress454** [comment]
Alright, turned out there was another place in Skipper that was using `.once()` to handle errors, and needed to be updated to use `.on()` instead so that multiple redundant errors wouldn't go uncaught.  That's been fixed and published in Skipper 0.6.5, and I was able to reproduce the issue with a failing test on skipper-s3 that now passes.  If anyone still gets this issue on Skipper >= 0.6.5, please post back here!

**Comment by rosygupta** [comment]
@sgress454 Worked by using this solution for skipper-disk: 

FYI the easiest way to test the updated code in your app is:

npm install github://balderdashy/skipper
and then in config/http.js:

module.exports.http = {
  bodyParser: require('skipper'),
  ...rest of file...
}
It's important that the bodyParser property be at the top level (module.exports.http), and not under the "middleware" property.

Thanks!

**Comment by sgress454** [comment]
@rosygupta Glad you got it working.  That solution (putting `bodyParser` directly under `http`) should only be necessary on versions of Sails before v0.12.  From v0.12 on, it should definitely go underneath `middleware`.

**Comment by SergioGeeK7** [comment]
Hi, my application crashes when I throw an error in the saveAs function 
`return next(new Error('File-type does not allow.'));`
I already tried to update skipper and required in http file... there's any solution to this to I can catch the error on whenDone function ?

```
function whenDone(err, uploadedFiles) {
            if (err) {
                var error = {  "status": 500, "error" : err };
                return res.serverError(error);
            }else {
```

**Comment by Dragons0458** [comment]
@SergioGeeK7 Hello, could you solve the problem?

**Comment by SergioGeeK7** [comment]
no, I wasn't able to solve properly. I just use the next ugly code to resolve the problem.

` const filename = 'resume';
    const upstream = req.file(filename);
    const files = upstream._files;
    upstream.on('error', (err) => console.log(err));
    if (!files[0]) {
      return saveUserSkills(req, res);
    }
    const errorMessage = validateFile(files);
    if (errorMessage) {
      return notify.send(res, notify.type.ERROR, errorMessage)
    }
    req.file(filename).upload(awsBucket, (err, files) => {
      if (err) {
        return notify.catch(res, err);
      }
      saveUserSkills(req, res, files[0].fd);
    });`

validateFile.js

`module.exports = (files) => {

    const upload = files[0].stream;
    const ext = path.extname(upload.filename);
    const byteCount = upload.byteCount;

    if (files.length > 1) {
      return skillMessages.oneFile;
    }
    if (fileSettings.allowedExt.indexOf(ext) === -1) {
      return skillMessages.fileType;
    }
    if (byteCount > fileSettings.maxBytes) {
      return skillMessages.maxBytes;
    }
    if(byteCount === 0) {
      return skillMessages.emptyResume;
    }
    return '';
}
`
if you found a better solution, please share it here

**Comment by Dragons0458** [comment]
It is a good solution, I will implement it while solving this bug.

If I find something I'll let you know, thank you very much!

**Comment by Pollocks01** [comment]
I was getting 'Request aborted' when using formidable and request when doing more than around 1 request per second: it was fine slower than that. I added header connection: 'keep-alive' and that fixed it.
Maybe off-topic but might help someone. This is where I got the idea from.

**Comment by kotmatpockuh** [comment]
Getting the same error with server-crash on Sails.js v1.0...
Any ideas how to solve?

**Comment by sgress454** [comment]
Hi all -- I'm locking this issue since it's gotten polluted with posts about several seemingly different problems.  If you're experiencing the original "abort" issue with Skipper, or a new issue, please make a new post with a detailed description and instructions to reproduce!
